# Generated by Django 5.0.6 on 2024-06-30 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 546728, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 546754, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 548860, tzinfo=datetime.timezone.utc), verbose_name='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 544449, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 544473, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 542340, tzinfo=datetime.timezone.utc), verbose_name='Joined at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 542411, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 543787, tzinfo=datetime.timezone.utc), verbose_name='Uploaded AT'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 548219, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='repliedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 56, 57, 548193, tzinfo=datetime.timezone.utc), verbose_name='Replied at'),
        ),
    ]
