# Generated by Django 5.0.6 on 2024-06-19 00:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 567858, tzinfo=datetime.timezone.utc), verbose_name='Followed at')),
                ('follower', models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Followed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280, verbose_name='Content')),
                ('postTime', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 569903, tzinfo=datetime.timezone.utc), verbose_name='Posted at')),
                ('updateTime', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 569927, tzinfo=datetime.timezone.utc), verbose_name='Updated at')),
                ('likes', models.ManyToManyField(related_name='liker', to=settings.AUTH_USER_MODEL, verbose_name='Liked By')),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('views', models.ManyToManyField(related_name='viewer', to=settings.AUTH_USER_MODEL, verbose_name='View By')),
            ],
            options={
                'ordering': ['-postTime'],
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='static/network/pictures', verbose_name='File')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 574345, tzinfo=datetime.timezone.utc), verbose_name='Uploaded at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded', to='network.post', verbose_name='Uploaded on')),
            ],
        ),
        migrations.CreateModel(
            name='hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=140, verbose_name='Hashtag')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded at')),
                ('post', models.ManyToManyField(related_name='post', to='network.post', verbose_name='Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=280, verbose_name='Comment')),
                ('commentedAt', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 572091, tzinfo=datetime.timezone.utc), verbose_name='Posted at')),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 572130, tzinfo=datetime.timezone.utc), verbose_name='Updated at')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commenter', to=settings.AUTH_USER_MODEL, verbose_name='Commented By')),
                ('likes', models.ManyToManyField(related_name='commentliker', to=settings.AUTH_USER_MODEL, verbose_name='Comment Liked by')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_post', to='network.post', verbose_name='Commented On')),
            ],
            options={
                'ordering': ['-commentedAt'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('pronouns', models.CharField(blank=True, choices=[('HH', 'He/Him'), ('SS', 'She/Her'), ('TT', 'They/Them'), ('HT', 'He/They'), ('ST', 'She/They'), ('IR', 'I rather not to say'), ('OT', 'Other')], default='She/They', max_length=2, verbose_name='Category')),
                ('bio', models.CharField(max_length=160, verbose_name='Bio')),
                ('joined', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 567108, tzinfo=datetime.timezone.utc), verbose_name='Joined at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 567148, tzinfo=datetime.timezone.utc), verbose_name='Updated at')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='static/network/profilePictures', verbose_name='File')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 569287, tzinfo=datetime.timezone.utc), verbose_name='Uploaded AT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=280, verbose_name='Reply')),
                ('repliedAt', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 573684, tzinfo=datetime.timezone.utc), verbose_name='Replied at')),
                ('UpdatedAt', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 29, 23, 573709, tzinfo=datetime.timezone.utc), verbose_name='Updated at')),
                ('repliedOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.comments', verbose_name='Replied to')),
                ('replier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replier', to=settings.AUTH_USER_MODEL, verbose_name='Replied by')),
            ],
            options={
                'ordering': ['-repliedAt'],
            },
        ),
    ]
