# Generated by Django 5.0.6 on 2024-06-27 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_followers_post_pictures_hashtags_comments_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 318923, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 318948, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 314567, tzinfo=datetime.timezone.utc), verbose_name='Followed at'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='static/network/pictures', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 321547, tzinfo=datetime.timezone.utc), verbose_name='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 316598, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 316621, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 313850, tzinfo=datetime.timezone.utc), verbose_name='Joined at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(choices=[('HH', 'He/Him'), ('SS', 'She/Her'), ('TT', 'They/Them'), ('HT', 'He/They'), ('ST', 'She/They'), ('IR', 'I rather not to say'), ('OT', 'Other')], default='IR', max_length=2, verbose_name='Pronouns'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 313886, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='picture',
            field=models.ImageField(upload_to='static/network/profilePictures', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 315893, tzinfo=datetime.timezone.utc), verbose_name='Uploaded AT'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 320573, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='repliedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 4, 17, 5, 320535, tzinfo=datetime.timezone.utc), verbose_name='Replied at'),
        ),
    ]
