# Generated by Django 5.0.6 on 2024-06-30 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_comments_commentedat_alter_comments_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 475045, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 475069, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 477030, tzinfo=datetime.timezone.utc), verbose_name='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 472803, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 472826, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 470760, tzinfo=datetime.timezone.utc), verbose_name='Joined at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 470827, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 472168, tzinfo=datetime.timezone.utc), verbose_name='Uploaded AT'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 476420, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='repliedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 21, 23, 23, 476395, tzinfo=datetime.timezone.utc), verbose_name='Replied at'),
        ),
    ]
