# Generated by Django 5.0.6 on 2024-07-15 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comments_commentedat_alter_comments_updatedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='repliedOn',
        ),
        migrations.RemoveField(
            model_name='hashtags',
            name='post',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replier',
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 5, 18, 6, 333368, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 5, 18, 6, 333382, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 5, 18, 6, 332178, tzinfo=datetime.timezone.utc), verbose_name='Joined at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 5, 18, 6, 332224, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 5, 18, 6, 332990, tzinfo=datetime.timezone.utc), verbose_name='Uploaded AT'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Hashtags',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
