# Generated by Django 5.0.6 on 2024-07-15 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_reply_repliedon_remove_hashtags_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 7, 40, 7, 93624, tzinfo=datetime.timezone.utc), verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 7, 40, 7, 93635, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 7, 40, 7, 92606, tzinfo=datetime.timezone.utc), verbose_name='Joined at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 7, 40, 7, 92640, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 7, 40, 7, 93334, tzinfo=datetime.timezone.utc), verbose_name='Uploaded AT'),
        ),
    ]
